// src/components/Nav.vue
<template>
  <div class="nav-wrapper">
        <div class="burger toggle">
            <span class="burger-mobile"></span>
        </div>
        <nav>
            <ul>
                <li>
                    <a href="#"> {{ nav1 }} </a>
                </li>
                <li>
                    <a href="#"> {{ nav2 }} </a>
                </li>
                <li>
                    <a href="#"> {{ nav3 }} </a>
                </li>
                <li>
                    <a href="#"> {{ nav4 }} </a>
                </li>
            </ul>
        </nav>
    </div>
</template>

<script>
export default {
  data() {
    return {
      nav1: 'HOME',
      nav2: 'ABOUT',
      nav3: 'WORK',
      nav4: 'BLOG'
    }
  }
};
</script>


<style lang='postcss'>
.nav-wrapper {
  display: grid;
  grid-template-columns: 1fr 1fr;
  position: fixed;
  right: 0;
  z-index: 3;
}

.burger {
  background: $black;
  border: 4px solid var(--dirty-white);
  height: 80px;
  width: 80px;
  position: absolute;
  top: 0;
  right: 0;
  z-index: 2;
  transition-property: border;
  transition-duration: 0.2s;

  & .burger-mobile {
    background: var(--blue);
    height: 7px;
    width: 45px;
    display: block;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    transition: 0.5s;
    transition-delay: 0.1s;
  }

  & .burger-mobile::before {
    content: "";
    position: absolute;
    width: 100%;
    height: 100%;
    background: var(--dirty-white);
    display: block;
    top: -15px;
    left: 0;
    transition-property: top, transform;
    transition-delay: 0.5s, 0;
    transition-duration: 0.5s, 0.5s;
  }

  & .burger-mobile::after {
    content: "";
    position: absolute;
    width: 100%;
    height: 100%;
    background: var(--yellow);
    display: block;
    top: 15px;
    left: 0;
    transition-property: top, transform;
    transition-delay: 0.5s, 0;
    transition-duration: 0.5s, 0.5s;
  }
}

.burger.active {
  border: 0;
}

.toggle.active span::before {
  background: var(--blue);
  top: 0;
  transform: rotate(45deg);
}

.toggle.active span::after {
  top: 0;
  transform: rotate(-45deg);
}

.toggle.active span {
  background: transparent;
}

nav {
  background: $black;
  color: var(--dirty-white);
  position: absolute;
  top: 0;
  right: 0;
  height: 100vh;
  width: 0;
  text-align: center;
  text-decoration: none;
  padding: 0;
  transition-duration: 0.5s;

  & ul {
    display: grid;
    justify-content: center;
    align-content: center;
    list-style-type: none;
    margin-top: 1em;
    padding-top: 20vh;

    & li {
      /* height: 80px; */

      & a {
        /* border: 4px solid $dirty-white; */
        color: var(--dirty-white);
        display: block;
        height: 80px;
        font-size: 1em;
        font-weight: bold;
        text-decoration: none;
      }
    }
  }
}

nav.active {
  width: 100vw;
  height: 100vh;
}

@media (min-width: 768px) {
  .burger {
    width: 160px;
    top: 40px;
    right: 40px;
  }

  nav {
    & ul {
      margin-top: 1em;

      & li {
        & a {
          font-size: 3em;
        }
      }
    }
  }

  nav.active {
    width: 30vw;
  }
}
</style>

// src/components/Nav.tsx
import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import styled from '@emotion/styled';
import './Nav.css';

const NavBurger = styled.div`
  box-sizing: border-box;
  color: var(--white);
  cursor: pointer;
  font-family: Audiowide, monospace;
  font-size: 20px;
  display: flex;
  justify-content: center;
  align-items: center;
  margin: 16px;
  position: absolute;
  right: 0;
  top: 0;
  height: 32px;
  width: 160px;
  z-index: 1;
  @media (max-width: 1000px) {
    font-size: 16px;
    margin: 0;
  }
`;

const NavCopy = styled.span`
  background: transparent;
  color: var(--white);
  font-size: 20px;
  margin-right: 8px;
  position: relative;
  text-shadow: 2px 2px 2px black;
  transition: all .4s;
  user-select: none;
    :before {
      content: attr(data-letters);
      position: absolute;
      z-index: 2;
      overflow: hidden;
      color: var(--blue);
      white-space: nowrap;
      width: 0;
      transition: width ease-in-out 0.4s;
    }
  :hover {
    :before {
     width: 100%;
    }
  }
`;

const NavMenu = styled.div`
  align-items: center;
  background: var(--black);
  color: var(--white);
  display: flex;
  flex-direction: column;
  font-family: Audiowide, monospace;
  font-size: 32px;
  height: 100vh;
  justify-content: center;
  list-style: none;
  position: absolute;
  right: 0;
  text-shadow: 2px 2px 2px black;
  top: 0;
  width: 0;
  & a {
    color: var(--white);
  }
  & a:visited {
    color: inherit;
    text-decoration: none;
  }
`;

const MenuItem = styled.li`
  align-items: center;
  display: flex;
  height: 80px;
  justify-content: center;
  margin: 6px;
  user-select: none;
  width: 160px;
`;

const StyledLink = styled(Link)`
  position: relative;
  text-decoration: none;
  transition: all .8s;
  user-select: none;
  :after {
    background: var(--yellow);
    border-radius: 1px;
    content: '';
    height: 0;
    left: -5%;
    position: absolute;
    top: 60%;
    transition: all 600ms;
    width: 110%;
    z-index: -1;
  }
  &:hover {
    text-decoration: underline;
    transform: scale(1.2);
    :after {
      height: 50%;
    }
  }
  &:focus {
    :after {
      background: var(--white);
      height: 1px;
      width: 10000px;
      left: -5000px;
    }
  }
`;

export const Nav = () => {
  const [display, setDisplay] = useState(false);
  const toggleNav = () => setDisplay(!display);

  return <nav>
    <NavBurger onClick={ toggleNav }>
      <NavCopy data-letters="_Menu">_Menu</NavCopy>
      <span className={ display ? 'burger active' : 'burger' }/>
    </NavBurger>
    <NavMenu className={ display ? 'menu active' : 'menu' }>
      <MenuItem key="Home">
        <StyledLink to="Home" onClick={ toggleNav }>Home</StyledLink>
      </MenuItem>
      <MenuItem key="About">
        <StyledLink to="About" onClick={ toggleNav }>About</StyledLink>
      </MenuItem>
      <MenuItem key="Blog">
        <StyledLink to="Blog" onClick={ toggleNav }>Blog</StyledLink>
      </MenuItem>
    </NavMenu>
  </nav>;
};
